<h1> Algoritmo do perceptron para duas entradas </h1> 
<h2> <br> Curso: Engenharia Elétrica <br> Disciplina: Sistemas Inteligentes<br>Professor: Carlos Roberto Jr </h2>

<h2> Importa bibliotecas </h2> 

In [4]:
from random import choice
from numpy import array, dot, random, set_printoptions
import time

<h2> Armazena dados de teste e treinamento </h2> 

In [5]:
training_data = [
    (array([0,0]), 0),
    (array([0,1]), 0),
    (array([1,0]), 0),
    (array([1,1]), 1),
]

test_data = [
    (array([0,0]), 0),
    (array([0,1]), 0),
    (array([1,0]), 0),
    (array([1,1]), 1),
]
print("training_data")
print(training_data)
print("test_data")
print(test_data)

training_data
[(array([0, 0]), 0), (array([0, 1]), 0), (array([1, 0]), 0), (array([1, 1]), 1)]
test_data
[(array([0, 0]), 0), (array([0, 1]), 0), (array([1, 0]), 0), (array([1, 1]), 1)]


<h2> Define variáveis </h2> 

In [6]:
# Define variável peso com valores aleatorios
w = random.rand(2)/2 -0.5

# Define a taxa de aprendizagem
a = 0.2
# Define o critério de parada
STOP = 0.01
# Cria variável para contar iterações
it = 0
# Cria a variável do erro quadrático médio
MSE = float(0.0)
# Cria a função degrau unitário
unit_step = lambda x: 0 if x <= 0.5 else 1
# E a magia de formatação de vetores acontece...
set_printoptions(precision=4)

<h2> Etapa de Treinamento </h2> 
<p>  Observações:Aprender uma lógica OR para o algoritmo é mais fácil do que aprender uma lógica AND.
Nos testes com logica AND são muitas iterações e não obtem um MSE satisfatório. O que pode ser feito para solucionar? </p>

In [7]:
# Realiza o laço enquanto MSE é alto ou se é a primeira iteração
while MSE > STOP or it == 0:
    it = it + 1
    print('\n---------- Iteracao: ',it)
    for i in range(4):
        # Seleciona uma amostra aleatória da base de dados
        x, d = choice(training_data)
        # Realiza a operação de soma do perceptron
        sum = dot(w, x)
        # Aplica a somatória na função de ativação
        y = unit_step(sum)
        # Calcula o erro
        e = d - y
        # Imprime os dados
        print("x: {} w: {} \t sum: {:.4} \t -> y: {} e: {}".format(x, w, sum, y, e))
        # Realiza o ajuste dos pesos do perceptron
        w += a * e * x
        # Imprime o peso corrigido
        print('w : {}'.format(w))
        # Apresenta os resultados 
        
    # Apos treinar com toda base de dados calcula o MSE
    print('\n--- Calcula o erro quadrático médio')
    MSE = 0
    for i in range(4):
        # Seleciona uma amostra sequencial da base de dados
        x, d = training_data[i]
        # Realiza a operação de soma do perceptron
        sum = dot(w, x)
        # Aplica a somatória na função de ativação
        y = unit_step(sum)
        # Calcula o erro do perceptron
        e = d - y
        # Calcula o erro quadrático médio
        MSE = MSE + e*e
        # Apresenta os resultados 
        print("{}: {:.4} \t-> {} \t [e = {}, MSE = {}]".format(x, sum, y, e, MSE))
    # O erro quadrático médio é multiplicado por 1/2
    MSE = MSE*0.5
    print("MSE = {:.4}".format(MSE))
    time.sleep(2)


---------- Iteracao:  1
x: [1 1] w: [-0.3868 -0.0012] 	 sum: -0.3881 	 -> y: 0 e: 1
w : [-0.1868  0.1988]
x: [1 0] w: [-0.1868  0.1988] 	 sum: -0.1868 	 -> y: 0 e: 0
w : [-0.1868  0.1988]
x: [0 0] w: [-0.1868  0.1988] 	 sum: 0.0 	 -> y: 0 e: 0
w : [-0.1868  0.1988]
x: [1 0] w: [-0.1868  0.1988] 	 sum: -0.1868 	 -> y: 0 e: 0
w : [-0.1868  0.1988]

--- Calcula o erro quadrático médio
[0 0]: 0.0 	-> 0 	 [e = 0, MSE = 0]
[0 1]: 0.1988 	-> 0 	 [e = 0, MSE = 0]
[1 0]: -0.1868 	-> 0 	 [e = 0, MSE = 0]
[1 1]: 0.01191 	-> 0 	 [e = 1, MSE = 1]
MSE = 0.5

---------- Iteracao:  2
x: [0 1] w: [-0.1868  0.1988] 	 sum: 0.1988 	 -> y: 0 e: 0
w : [-0.1868  0.1988]
x: [1 1] w: [-0.1868  0.1988] 	 sum: 0.01191 	 -> y: 0 e: 1
w : [0.0132 0.3988]
x: [0 0] w: [0.0132 0.3988] 	 sum: 0.0 	 -> y: 0 e: 0
w : [0.0132 0.3988]
x: [1 0] w: [0.0132 0.3988] 	 sum: 0.01315 	 -> y: 0 e: 0
w : [0.0132 0.3988]

--- Calcula o erro quadrático médio
[0 0]: 0.0 	-> 0 	 [e = 0, MSE = 0]
[0 1]: 0.3988 	-> 0 	 [e = 0, MSE = 0]

<h2> Etapa de Testes </h2> 

In [8]:
# Para cada amostra da base de treinamento
for x, _ in test_data:
    # Realiza a operação de somatória
    sum = dot(x, w)
    # Calcula a saída do perceptron
    y = unit_step(sum)
    # Imprime os resultados
    print("{}: {:6} \t-> {}".format(x, round(sum,2), y))

[0 0]:    0.0 	-> 0
[0 1]:    0.4 	-> 0
[1 0]:   0.21 	-> 0
[1 1]:   0.61 	-> 1
